version: "3"
services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile.playwright
      args:
        - PLAYWRIGHT_VERSION=${PLAYWRIGHT_VERSION}
    volumes:
      - .:/app
    user: pwuser
    working_dir: /app
    command: pnpm test:${TEST_TYPE}:local
    environment:
      - UPDATE_TAPES=${UPDATE_TAPES:-false}
